/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.Test1;

public class AppTest1 {
    public String getGreeting() {
        return "Hello World4!";
    }

    public static void main(String[] args) {
        System.out.println(new AppTest1().getGreeting());
    }
}
