cc_test(
    name = "greetings_tests",
    srcs = ["greetings_test.cc", "hello_test.cc"],
    deps = [
        "//src/lib:greetings_lib",
        "@com_google_googletest//:gtest_main"
    ],
)
cc_test(
    name = "unit_test_samples_tests",
    srcs = ["unit_test/sample_test.cc"],
    deps = [
        "//src/main:unit_test_samples_lib",
        "@com_google_googletest//:gtest_main"
    ],
)
