/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class AppNew {
    public String getGreeting() {
        return "Hello Worldi New!";
    }

    public static void main(String[] args) {
        System.out.println(new AppNew().getGreeting());
    }
}
