package org.example.models;

public enum ResponseNodeCode {
    BASELINER_TARGET_STATE_VALIDATION,
    BASELINER_ENTITY_RESOURCE_STATE_VALIDATION,
    BASELINER_CONSTRAINT_VALIDATION,
    BASELINER_CHILD_COUNT_VALIDATION
}
