/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App1 {
    public String getGreeting() {
        return "Hello World2!";
    }

    public static void main(String[] args) {
        System.out.println(new App1().getGreeting());
    }
}
