cc_binary(
    name = "DPMain",
    srcs = ["cpp/main.cpp"],
)

cc_binary(
    name = "MaxSubSequenceSumNonAdjacent",
    srcs = ["cpp/main.cpp", "cpp/DP/MaxSubSequenceNonAdjacentTest.cpp"],
    copts = ["-Iheaders"],
)
