/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.Test2;

public class AppTest2 {
    public String getGreeting() {
        return "Hello World3!";
    }

    public static void main(String[] args) {
        System.out.println(new AppTest2().getGreeting());
    }
}
